name: Trigger auto deployment for jazk-pythoncontainer-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/jazk-pythoncontainer-app-AutoDeployTrigger-8cd52cb8-05bf-44a1-afc5-5da5161af7f5.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.JAZKPYTHONCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: jazkregistry.azurecr.io
          registryUsername: ${{ secrets.JAZKPYTHONCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.JAZKPYTHONCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: jazk-pythoncontainer-app
          resourceGroup: jazk-pythoncontainer-rg
          imageToBuild: jazkregistry.azurecr.io/jazk-pythoncontainer-app:${{ github.sha }}
          

     

